default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: retropenbase_dev

test:
  <<: *default
  database: retropenbase_test

production:
  <<: *default
  database: retropenbase_prod
