fetch_broken_discord_users:
  cron: '0 3 * * * Europe/Paris'
  queue: :discord
  class: 'FetchBrokenDiscordUsersJob'

fetch_broken_discord_guilds:
  cron: '0 4 * * * Europe/Paris'
  queue: :discord
  class: 'FetchBrokenDiscordGuildsJob'
